"%~dp0\s-luna-empire" stop
"%~dp0\s-luna-double-representation" stop
"%~dp0\s-luna-undo-redo" stop
"%~dp0\s-luna-ws-connector" stop
"%~dp0\s-luna-broker" stop
"%~dp0\s-luna-empire" uninstall
"%~dp0\s-luna-double-representation" uninstall
"%~dp0\s-luna-undo-redo" uninstall
"%~dp0\s-luna-ws-connector" uninstall
"%~dp0\s-luna-broker" uninstall
